# Generated by Django 3.2.13 on 2022-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0003_auto_20220815_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='begin',
            field=models.DateField(db_index=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Страна местонахождения на момент приема'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fname',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='iname',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='oname',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Отчество'),
        ),
    ]
